# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "todaywasawesome/metallb-google-wifi-announce"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "todaywasawesome/metallb-google-wifi-announce"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    registry: todaywasawesome
    stage: "build"

  push:
    type: push
    arguments:
      candidate: '${{build}}'
      tags: 
      - latest
      - ${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}
      - ${{CF_SHORT_REVISION}}
      image_name: todaywasawesome/metallb-google-wifi-announce
      registry: todaywasawesome
      stage: "build"


